{% set version = '1.3.12' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-emdbook
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/emdbook_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/emdbook/emdbook_{{ version }}.tar.gz
  sha256: 0646caf9e15aaa61ff917a4b5fdf82c06ac17ef221a61dec3fbb554e7bff4353

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-bbmle
    - r-coda
    - r-lattice
    - r-plyr
  run:
    - r-base
    - r-mass
    - r-bbmle
    - r-coda
    - r-lattice
    - r-plyr

test:
  commands:
    - $R -e "library('emdbook')"           # [not win]
    - "\"%R%\" -e \"library('emdbook')\""  # [win]

about:
  home: http://www.math.mcmaster.ca/bolker/emdbook
  license: GPL-3
  summary: Auxiliary functions and data sets for "Ecological Models and Data", a book presenting
    maximum likelihood estimation and related topics for ecologists (ISBN 978-0-691-12522-0).
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: emdbook
# Type: Package
# Title: Support Functions and Data for "Ecological Models and Data"
# Version: 1.3.12
# LazyData: yes
# Authors@R: c(person("Ben","Bolker",email="bolker@mcmaster.ca", role=c("aut","cre")), person("Sang Woo","Park",role="ctb"), person("James","Vonesh",role="dtc"), person("Jacqueline","Wilson",role="dtc"), person("Russ","Schmitt",role="dtc"), person("Sally","Holbrook",role="dtc"), person("James D.","Thomson",role="dtc"), person("R. Scot","Duncan",role="dtc") )
# Description: Auxiliary functions and data sets for "Ecological Models and Data", a book presenting maximum likelihood estimation and related topics for ecologists (ISBN 978-0-691-12522-0).
# Suggests: R2jags, ellipse, SuppDists, numDeriv, testthat, rgl
# Imports: MASS, lattice, plyr, coda, bbmle
# License: GPL
# URL: http://www.math.mcmaster.ca/bolker/emdbook
# NeedsCompilation: no
# Packaged: 2020-02-19 15:32:30 UTC; bolker
# Author: Ben Bolker [aut, cre], Sang Woo Park [ctb], James Vonesh [dtc], Jacqueline Wilson [dtc], Russ Schmitt [dtc], Sally Holbrook [dtc], James D. Thomson [dtc], R. Scot Duncan [dtc]
# Maintainer: Ben Bolker <bolker@mcmaster.ca>
# Repository: CRAN
# Date/Publication: 2020-02-19 16:50:02 UTC
