travis:
  secure:
    BINSTAR_TOKEN: eSJYc0veJusfnanUxPEhSpJsIDh1p+mmwSBHr6F8bDce0ntwd4JIiiFRb8GHvUdWkaItNjHIdCtxFpRpQLbrqT8p/6P5cZwRpaRQFHu5wdVfdHCFR1gD5EqlHBpWBaqVQiM/spxy7jt/K43IGNQjfYo/rYw8eULpjPqgzjwpHDElNU+mCt4xc9wsRem2pP8cQ4CYdzp/HbuGDy/EgRF+rAyGrpn/f6VqkNZgSbV/HMC2wEHrpdl/ptaNOD+4Ym2VEwMX1Zfvvl5jga5/NivA7moVQlVo8nAArqWBQ2dAwFHCGTxLK6ok5AJB3gq0Ep6trmv9fNd9p/r76bknmBy/9UOrjw+QXMktQZWfHFASJ+N5ovAfrKiNHhAfbBmCEb43YKvQHOSXtFzN1St7UZr0XBXFBcp+wTNrfWzUY/nR/sPl3fxgZDMO9vzNs1HdYkVQBW9NmpacSsWZ8f+CW02PXyBjSMmPBUHx4p0UuRTm7GjQuVmYE5dzANomr9KniE57a+geimh4oxa0HmUi5iNy+smI5k7OO0xfUitaxEMs4Am+hHDsTh27Jz1I0PtoF1mSktpMew+q8WzgFqOIbI7LYaX3EHC4iMdPTGAo5dElk6OiyWXyNuOiAiG5C12bHjrzdG++d4+D+RBSrf+KTePTu8K+A+w8sxTyynwF1JG0/kc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
